In [ ]:
# DNN으로 MNIST 데이터 분류하기

In [ ]:
import tensorflow.keras.datasets as datasets

# MNIST 데이터셋 로드
(X_train, y_train), (X_test, y_test) = datasets.mnist.load_data()

# MNIST 데이터셋 출력 
# print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)
# print(X_train[0])
# print(y_train[0])

5


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Input

# 모델 구성
model = Sequential()

## 입력층
model.add(Input(shape=(784,)))

## 은닉층 
model.add(Dense(256, activation='relu'))
model.add(Dense(128, activation='relu'))

## 출력층
model.add(Dense(10, activation='softmax'))

## 모델 요약
model.summary()

2025-09-15 19:50:14.204069: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M4 Pro
2025-09-15 19:50:14.204092: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 24.00 GB
2025-09-15 19:50:14.204096: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 8.00 GB
2025-09-15 19:50:14.204107: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2025-09-15 19:50:14.204116: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 256)            │       200,960 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 10)             │         1,290 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 235,146 (918.54 KB)

 Trainable params: 235,146 (918.54 KB)

 Non-trainable params: 0 (0.00 B)

In [3]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [ ]:

# Dense() 층에 입력할 수 있도록 28x28 이미지를 784 크기의 벡터로 변환
# 60000x28x28 -> 60000x784 배열로 변환 (3차원 --> 2차원) --> Dense 층에는 입력 데이터로 1차원 벡터만을 지원하기 때문
# 0~255 사이의 픽셀 값을 0~1 사이의 값으로 정규화
X_train = X_train.reshape(-1, 784) / 255.0
X_test = X_test.reshape(-1, 784) / 255.0

# 모델 학습
model.fit(X_train, y_train, epochs=5, batch_size=32, validation_split=0.2)

(60000, 784)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
# 모델 평가
model.evaluate(X_test, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8172 - loss: 30.0046


[30.00464630126953, 0.8172000050544739]